title: "Practical Natural Language Processing with Ruby"
email: "arbox@yandex.com"
baseurl: ""
twitter_username: "@rubynlp"
github_username:  "arbox"
markdown: kramdown
theme: minima
google_analytics: "UA-91420426-1"
description: >
  Natural Language Processing done with Ruby
